- name: Add apt repositories
  apt_repository: repo={{item}} state=present
  with_items:
    - deb http://ftp.us.debian.org/debian/ jessie main contrib non-free
    - deb-src http://ftp.us.debian.org/debian/ jessie main contrib non-free
    - deb http://security.debian.org/ jessie/updates main contrib non-free
    - deb-src http://security.debian.org/ jessie/updates main contrib non-free
    - deb http://ftp.us.debian.org/debian/ jessie-updates main contrib non-free
    - deb-src http://ftp.us.debian.org/debian/ jessie-updates main contrib non-free
    - deb http://ftp.us.debian.org/debian jessie-backports main
    - deb-src http://ftp.us.debian.org/debian jessie-backports main
    - deb http://repository.spotify.com stable non-free
    - deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main

- name: Add apt keys
  apt_key: keyserver=keyserver.ubuntu.com id={{item}}
  with_items:
    - 93C4A3FD7BB9C367
    - BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: Update apt cache and install packages
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - git
    - vim
    - build-essential
    - xorg
    - xorg-dev
    - suckless-tools
    - pandoc
    - evince
    - firefox-esr
    - thunar
    - laptop-mode-tools
    - xclip
    - xfce4-notifyd
    - xfce4-volumed
    - awesome
    - pulseaudio
    - xbindkeys
    - texlive
    - xdotool
    - curl
    - redshift
    - transmission
    - firmware-linux-nonfree
    - firmware-atheros
    - spotify-client
    - zip
    - djvulibre-bin
    - imagemagick
    - speedtest-cli
    - vlc

- name: Set GRUB_TIMEOUT=0
  lineinfile: dest=/etc/default/grub regexp=^GRUB_TIMEOUT= line=GRUB_TIMEOUT=0
  notify: Update grub

- name: Create /etc/X11/xorg.conf.d
  file: path=/etc/X11/xorg.conf.d state=directory

- name: Configure synaptics
  template:
    src=templates/70-synaptics.conf.j2
    dest=/etc/X11/xorg.conf.d/70-synaptics.conf

- name: Clone dotfile repo
  git:
    repo: git://github.com/flowre/.home.git
    dest: ~/.home.git
    bare: yes

- name: Clone utilities repo
  git:
    repo: git://github.com/flowre/utilities.git
    dest: ~/src/utilities

- name: Clone vim plugin repos
  git: repo=git://github.com/{{item}} dest=~/.vim/bundle
  with_items:
    - plasticboy/vim-markdown.git
    - pbrisbin/vim-mkdir.git
    - derekwyatt/vim-scala

- name: Install ~/.bash_profile
  template: src=templates/.bash_profile.j2 dest=~/.bash_profile

- name: Install ~/.xsession
  template: src=templates/.xsession.j2 dest=~/.xsession

- name: Install packages to allow apt to use a repo over HTTPS
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add docker GPG key
  apt_key: url=https://apt.dockerproject.org/gpg

- name: Add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo/ debian-jessie main
    state: present

- name: Install docker
  apt: name=docker-engine state=latest update_cache=yes

#- name: Install utilities
#  shell: make install
#  args:
#    chdir: ~/src/utilities

#- name: Setup backlight utility
#  shell: systemctl mask systemd-backlight@backlight:acpi_video0.service
#  file: path=/sys/class/backlight/radeon_bl0/brightness owner=felix

#usermod -a -G netdev felix # TODO: is this needed?
# TODO: install /etc/wpa_supplicant.conf
# TODO: install or merge /etc/network/interfaces
# TODO: remove read permissions for group and system for
#/etc/network/interfaces in order to make wpa_supplicant work

# TODO: install .ssh/config

# TODO: install firefox profile

# TODO: install thunar settings

# TODO: changed Transmission download location. Could possibly just change in 
#.config/transmission/settings.json
